### ISSUE TITLE
使用时报错：Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by gapplef** [YuyingWu/hexo-tag-douban#2]
环境：
`> hexo -v`
```shell
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.15.0-42-generic linux x64
http_parser: 2.8.0
node: 10.14.2
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```
想在读书笔记中插入豆瓣条目，找到了这个扩展，
正常安装并在文章中插入标签，预览博客时报错：
```shell
undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/.../blog/node_modules/hexo-tag-douban/index.js:52:25)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
似乎是说输入给JSON.parse()的数据不满足json规范。

**Comment by YuyingWu** [comment]
@gapplef 刚刚发布了1.0.4版本，修复了这个问题，目前douban的开发者页面貌似挂了，原本插件里带了我申请的个人api token，请求403了，我把token去掉，就好了。

后续我会看看有没有别的可替代的API能提供书籍的信息。

**Comment by gapplef** [comment]
@YuyingWu 非常感谢，更新后没有问题了。
我使用的主题是Next，这是效果：
![screenshot from 2019-01-08 19-30-17](https://user-images.githubusercontent.com/5604665/50828279-deb7bf80-137b-11e9-8950-fc527bdc1402.png)
有两个问题：
+ Github和豆瓣的图标大小不一致
+ 底部有一条线条(应该是Next主题下链接的默认样式)

请问如何解决？
- - - -
**Update**
第一个问题是错觉，是因为Github图标外边又一圈空白，显得更小 :joy: 
问题只有第二个，Next主题默认会在链接下加一条下划线，请问该如何处理？

**Comment by YuyingWu** [comment]
哈哈，logo的大小问题，我再认真看看。

底部有一条线，你可以把你的网站贴上来么，我看看？

**Comment by gapplef** [comment]
@YuyingWu 网站https://yelf.me ，但我还没有推送，只是在本地预览，需要提供什么信息呢？

**Comment by YuyingWu** [comment]
@gapplef 噢噢，你还没有上线。ok，那我用一个空的next主题测试一下吧~
你也可以先调试一下哈，欢迎来fork，哈哈！

**Comment by gapplef** [comment]
@YuyingWu 我只用Python做科学计算，为了写博客才了解一点HTML，不是很懂前端。
这是对应的HTML源文件：
```html
<div class="hexo-tag-douban" style="position:relative;width:60%;border:1px solid #666;border-radius: 4px;margin:10px auto;padding: 10px;">
  <a href="https://book.douban.com/subject/25934182/" target="_blank" style="color: #666;display:block;">
    <img src="https://img3.doubanio.com/view/subject/m/public/s28946675.jpg?apikey=0e13da30b101d57c2a3b8e9213058074" alt="如何阅读一本书" style="width: 135px; height: 192px; display:inline-block; margin-right: 14px;" referrerpolicy="no-referrer">
    <div class="info" style="display:inline-block; vertical-align: top;">
      <p style="margin:0; font-size: 14px;">书名：如何阅读一本书</p>
      <p style="margin:0; font-size: 14px;width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;" title="商务印书馆">出版社：商务印书馆</p>
      <p style="margin:0; font-size: 14px;">出版日期：2014-10-1</p>
      <p style="margin:0; font-size: 14px;">作者：莫提默·J.艾德勒,查尔斯·范多伦</p>
      <p style="margin:0; font-size: 14px;">译者：郝明义,朱衣</p>
      <p style="margin:0; font-size: 14px;">出版年：2014-10-1</p>
      <p style="margin:0; font-size: 14px;">定价：56.00元</p>
    </div>
  </a>
  <div style="background: url(https://img3.doubanio.com/pics/douban-icons/favicon_24x24.png);width: 24px;height: 24px;position: absolute;right: 10px;bottom: 10px;text-decoration-line:none;"></div>
  <a href="https://github.com/YuyingWu/hexo-tag-douban" title="hexo-tag-douban" target="_blank" style="display:block;width:24px;height:24px;position: absolute; bottom:10px;right: 39px;text-decoration-line:none;"><img src="https://github.com/fluidicon.png" alt="" style="display:block;width:24px;height:24px;"></a>
</div>
```
利用排除法可以确定问题源自第一个链接：
```html
<a href="https://book.douban.com/subject/25934182/" target="_blank" style="color: #666;display:block;">  ... </a>
```
但是即使在style中加入`text-decoration-line:none;`也无效，不清楚为什么。
一个有效的解决办法是将这个链接放在豆瓣的图标上而不是整个页面上，即：
```html
<div class="hexo-tag-douban" style="position:relative;width:60%;border:1px solid #666;border-radius: 4px;margin:10px auto;padding: 10px;">
  <img src="https://img3.doubanio.com/view/subject/m/public/s28946675.jpg?apikey=0e13da30b101d57c2a3b8e9213058074" alt=" " style="width: 135px; height: 192px; display:inline-block; margin-right: 14px;" referrerpolicy="no-referrer">
  <div class="info" style="display:inline-block; vertical-align: top;">
    <p style="margin:0; font-size: 14px;">书名：如何阅读一本书</p>
    <p style="margin:0; font-size: 14px;width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;" title="商务印书馆">出版社：商务印书馆</p>
    <p style="margin:0; font-size: 14px;">出版日期：2014-10-1</p>
    <p style="margin:0; font-size: 14px;">作者：莫提默·J.艾德勒,查尔斯·范多伦</p>
    <p style="margin:0; font-size: 14px;">译者：郝明义,朱衣</p>
    <p style="margin:0; font-size: 14px;">出版年：2014-10-1</p>
    <p style="margin:0; font-size: 14px;">定价：56.00元</p>
  </div>
  <a href="https://github.com/YuyingWu/hexo-tag-douban" title="hexo-tag-douban" target="_blank" style="display:block;width:24px;height:24px;position: absolute; bottom:10px;right: 39px;text-decoration-line:none;"><img src="https://github.com/fluidicon.png" alt="" style="display:block;width:24px;height:24px;"></a>
  <a href="https://book.douban.com/subject/25934182/" target="_blank" style="display:block;width:24px;height:24px;position: absolute;right: 10px;bottom: 10px;text-decoration-line:none;"><img src="https://img3.doubanio.com/pics/douban-icons/favicon_24x24.png" alt="" style="display:block;width:24px;height:24px;" /></a>
</div>
```
效果如下图，其中使得下划线不出现的语句是`height:24px;` :joy: 
![screenshot from 2019-01-08 21-58-14](https://user-images.githubusercontent.com/5604665/50835055-9f479e00-1390-11e9-9174-9871e3862e5b.png)
虽然不清楚为什么总是有下划线，但这样至没问题了。而且有两点好处：
+ 之前豆瓣的图标不能点，现在豆瓣图标和Github图标刚好对应，都可以点。
+ 之前豆瓣图标显得更大，现在豆瓣图标外边也有一圈空白，不再那么突兀。

莫名其妙的解决了第一个问题 :rofl:

**Comment by gapplef** [comment]
上述做法的一个缺点是在开启fancybox后排版会乱，原先的做法则不会，不清楚为什么。
![screenshot from 2019-01-08 22-29-46](https://user-images.githubusercontent.com/5604665/50836851-331b6900-1395-11e9-822c-0d3f27c62dd7.png)

**Comment by YuyingWu** [comment]
@gapplef 好的，谢谢你提供的思路哈，哈哈，我也看看~
